{
   "owner" : "agua",
   "location" : "bin/cacheensembl",
   "executor" : "",
   "installdir" : "/aguadev/apps/emboss",
   "version" : "6.4.0.0",
   "name" : "cacheensembl",
   "localonly" : "0",
   "description" : "Generates server cache file for an Ensembl server",
   "package" : "emboss",
   "parameters" : [
      {
         "locked" : null,
         "value" : "server.$(servername)",
         "args" : "",
         "chained" : 0,
         "description" : "Server cache output file",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-cachefile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "outfile",
         "param" : "cachefile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "stdout",
         "args" : "",
         "chained" : 0,
         "description" : "Output file name",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-outfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "outfile",
         "param" : "outfile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Server name (Any string)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-servername",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "servername",
         "paramFunction" : ""
      }
   ],
   "linkurl" : "http://emboss.sourceforge.net/apps/release/6.4/emboss/apps/cacheensembl.html",
   "ordinal" : 0,
   "notes" : "",
   "url" : "http://www.ebi.ac.uk/Tools/emboss",
   "type" : "server"
}

