{
   "owner" : "agua",
   "location" : "bin/dbxflat",
   "executor" : "",
   "installdir" : "/aguadev/apps/emboss",
   "version" : "6.4.0.0",
   "name" : "dbxflat",
   "localonly" : "0",
   "description" : "Index a flat file database using b+tree indices",
   "package" : "emboss",
   "parameters" : [
      {
         "locked" : null,
         "value" : "00/00/00",
         "args" : "",
         "chained" : 0,
         "description" : "Index date (Date string dd/mm/yy)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-date",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "date",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Basename for index files (Any string from 2 to 19 characters, matching regular expression /[A-z][A-z0-9_]+/)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-dbname",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "dbname",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Resource name (Any string from 2 to 19 characters, matching regular expression /[A-z][A-z0-9_]+/)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-dbresource",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "dbresource",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : ".",
         "args" : "",
         "chained" : 0,
         "description" : "Database directory",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-directory",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "directory",
         "param" : "directory",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Wildcard filename(s) to exclude (Any string)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-exclude",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "exclude",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "id,acc",
         "args" : "",
         "chained" : 0,
         "description" : "Index fields (Values: id (ID); acc (Accession number); sv (Sequence Version and GI); des (Description); key (Keywords); org (Taxonomy))",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-fields",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "menu",
         "param" : "fields",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "*.dat",
         "args" : "",
         "chained" : 0,
         "description" : "Wildcard database filename (Any string)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-filenames",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "filenames",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "SWISS",
         "args" : "",
         "chained" : 0,
         "description" : "Entry format (Values: EMBL (EMBL); SWISS (Swiss-Prot, SpTrEMBL, TrEMBLnew); GB (Genbank, DDBJ); REFSEQ (Refseq); FASTQ (Fastq files))",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-idformat",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "menu",
         "param" : "idformat",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : ".",
         "args" : "",
         "chained" : 0,
         "description" : "Index file output directory",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-indexoutdir",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "outdir",
         "param" : "indexoutdir",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "Y",
         "args" : "",
         "chained" : 0,
         "description" : "Compressed index files",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-nocompressed",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "nocompressed",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "*.dbxflat",
         "args" : "",
         "chained" : 0,
         "description" : "General log output file",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-outfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "outfile",
         "param" : "outfile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "0.0",
         "args" : "",
         "chained" : 0,
         "description" : "Release number (Any string up to 9 characters)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-release",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "release",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "N",
         "args" : "",
         "chained" : 0,
         "description" : "Report I/O statistics for each input file",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-statistics",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "statistics",
         "paramFunction" : ""
      }
   ],
   "linkurl" : "http://emboss.sourceforge.net/apps/release/6.4/emboss/apps/dbxflat.html",
   "ordinal" : 0,
   "notes" : "",
   "url" : "http://www.ebi.ac.uk/Tools/emboss",
   "type" : "index"
}

