{
   "owner" : "agua",
   "location" : "bin/aligners/TOPHAT.pl",
   "executor" : "/usr/bin/perl",
   "installdir" : "/agua/0.6/t/bin/Agua/Ops/Install/outputs/bioapps",
   "version" : "0.6.0",
   "name" : "TOPHAT",
   "localonly" : "0",
   "description" : "A wrapper script to run TOPHAT (which uses Bowtie) to do fast short read alignment against a reference sequence",
   "package" : "bioapps",
   "parameters" : [
      {
         "locked" : "0",
         "value" : "%project%/%workflow%/coverage.wig",
         "args" : "",
         "description" : "A UCSC BedGraph wigglegram track, showing the depth of coverage at each position, including the spliced read alignments.",
         "discretion" : "Discretion",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "",
         "format" : "",
         "paramtype" : "output",
         "valuetype" : "file",
         "category" : "coverage",
         "param" : "coverage",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Max. number of cpus per job (1 to 4) (DEFAULT = 4)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--cpus",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "cpus",
         "param" : "cpus",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "200",
         "args" : "",
         "description" : "The  mean inner distance between first read and its mate pair (corresponds to -r/--mate-inner-dist argument to Tophat)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--distance",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "distance",
         "param" : "distance",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "%project%/%workflow%/accepted_hits.sam",
         "args" : "",
         "description" : "A list of read alignments in SAM format. SAM is a compact short read alignment format that is increasingly being adopted.",
         "discretion" : "Discretion",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "",
         "format" : "",
         "paramtype" : "output",
         "valuetype" : "file",
         "category" : "hits",
         "param" : "hits",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Comma-separated *sequence.txt file names (e.g., s_1_1_sequence.txt,s_2_1_sequence.txt)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--inputfiles",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "inputfiles",
         "param" : "inputfiles",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Max. number of concurrent cluster jobs (DEFAULT = 30)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--jobs",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "jobs",
         "param" : "jobs",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "%project%/%workflow%/junctions.bed",
         "args" : "",
         "description" : "A UCSC BED track of junctions reported by TopHat. Each junction consists of two connected BED blocks, where each block is as long as the maximal overhang of any read spanning the junction. The score is the number of alignments spanning the junction.",
         "discretion" : "Discretion",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "",
         "format" : "",
         "paramtype" : "output",
         "valuetype" : "file",
         "category" : "junctions",
         "param" : "junctions",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Keep intermediate files",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--keep",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "flag",
         "category" : "keep",
         "param" : "keep",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Name to used to submit jobs to cluster (e.g., tophat-sample1)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--label",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "label",
         "param" : "label",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Comma-separated *sequence.txt mate file names (e.g., s_1_2_sequence.txt,s_2_2_sequence.txt) with locations as paths relative to the output directory",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--matefiles",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "matefiles",
         "param" : "matefiles",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Create this directory and write output files to it",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--outputdir",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "outputdir",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "%project%/%workflow%/out.sam",
         "args" : "",
         "description" : "SAM file containing",
         "discretion" : "Discretion",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "",
         "format" : "sam",
         "paramtype" : "output",
         "valuetype" : "file",
         "category" : "outputfile",
         "param" : "outputfile",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Additional parameters to be passed to tophat (e.g., --solexa1.3-quals",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--params",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "params",
         "param" : "params",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Cluster queue options",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--queue",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "queue",
         "param" : "queue",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Location of indexed reference file  (NB: Use file stub, e.g., /some/path/hg19)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--reference",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "reference",
         "param" : "reference",
         "paramFunction" : ""
      }
   ],
   "ordinal" : null,
   "notes" : "Uses Tophat v 0.1.12 and Bowtie v 0.12.2",
   "url" : "http://www.aguadev.org/confluence/display/howto/Bioapps+API",
   "type" : "expression"
}

