{
   "owner" : "agua",
   "location" : "bin/dan",
   "executor" : "",
   "installdir" : "/aguadev/apps/emboss",
   "version" : "6.4.0.0",
   "name" : "dan",
   "localonly" : "0",
   "description" : "Calculates nucleic acid melting temperature",
   "package" : "emboss",
   "parameters" : [
      {
         "locked" : null,
         "value" : "50.",
         "args" : "",
         "chained" : 0,
         "description" : "Enter DNA concentration (nM) (Number from 1.000 to 100000.000)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-dnaconc",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "decimal",
         "category" : "decimal",
         "param" : "dnaconc",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "0.",
         "args" : "",
         "chained" : 0,
         "description" : "This specifies the percent formamide to be used in calculations (it is ignored unless -product is used). (Number from 0.000 to 100.000)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-formamide",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "decimal",
         "category" : "decimal",
         "param" : "formamide",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "$EMBOSS_GRAPHICS value, or x11",
         "args" : "",
         "chained" : 0,
         "description" : "Graph type (ps, hpgl, hp7470, hp7580, meta, cps, x11, tek, tekt, none, data, xterm, svg)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-graph",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "ps|hpgl|hp7470|hp7580|meta|cps|x11|tek|tekt|none|data|xterm|svg",
         "category" : "outgraph",
         "param" : "graph",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "55.",
         "args" : "",
         "chained" : 0,
         "description" : "Enter a minimum value for the temperature scale (y-axis) of the plot. (Number from 0.000 to 150.000)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-mintemp",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "decimal",
         "category" : "decimal",
         "param" : "mintemp",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "0.",
         "args" : "",
         "chained" : 0,
         "description" : "This specifies the percent mismatch to be used in calculations (it is ignored unless -product is used). (Number from 0.000 to 100.000)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-mismatch",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "decimal",
         "category" : "decimal",
         "param" : "mismatch",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "*.dan",
         "args" : "",
         "chained" : 0,
         "description" : "If a plot is not being produced then data on the melting point etc. in each window along the sequence is output to the file. (default -rformat seqtable)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-outfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "outfile",
         "param" : "outfile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "If this is not specified then the file of output data is produced, else a plot of the melting point along the sequence is produced.",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-plot",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "toggle",
         "param" : "plot",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "Window size (20)",
         "args" : "",
         "chained" : 0,
         "description" : "This specifies the product length to be used in calculations (it is ignored unless -product is used). (Any integer value)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-prodlen",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "prodlen",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "This prompts for percent formamide, percent of mismatches allowed and product length.",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-product",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "toggle",
         "param" : "product",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "This specifies that the sequence is an RNA sequence and not a DNA sequence.",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-rna",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "rna",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "50.",
         "args" : "",
         "chained" : 0,
         "description" : "Enter salt concentration (mM) (Number from 1.000 to 1000.000)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-saltconc",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "decimal",
         "category" : "decimal",
         "param" : "saltconc",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Nucleotide sequence(s) filename and optional format, or reference (input USA)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-sequence",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "seqall",
         "param" : "sequence",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "1",
         "args" : "",
         "chained" : 0,
         "description" : "This is the amount by which the window is moved at each increment in order to find the melting point and other properties along the sequence. (Integer 1 or more)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-shiftincrement",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "shiftincrement",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "25.",
         "args" : "",
         "chained" : 0,
         "description" : "If -thermo has been specified then this specifies the temperature at which to calculate the DeltaG, DeltaH and DeltaS values. (Number from 0.000 to 100.000)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-temperature",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "decimal",
         "category" : "decimal",
         "param" : "temperature",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Output the DeltaG, DeltaH and DeltaS values of the sequence windows to the output data file.",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-thermo",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "toggle",
         "param" : "thermo",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "20",
         "args" : "",
         "chained" : 0,
         "description" : "The values of melting point and other thermodynamic properties of the sequence are determined by taking a short length of sequence known as a window and determining the properties of the sequence in that window. The window is incrementally moved along the sequence with the properties being calculated at each new position. (Integer from 1 to 100)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-windowsize",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "windowsize",
         "paramFunction" : ""
      }
   ],
   "linkurl" : "http://emboss.sourceforge.net/apps/release/6.4/emboss/apps/dan.html",
   "ordinal" : 0,
   "notes" : "",
   "url" : "http://www.ebi.ac.uk/Tools/emboss",
   "type" : "nucleotide"
}

