{
   "owner" : "agua",
   "location" : "bin/showserver",
   "executor" : "",
   "installdir" : "/aguadev/apps/emboss",
   "version" : "6.4.0.0",
   "name" : "showserver",
   "localonly" : "0",
   "description" : "Displays information on configured servers",
   "package" : "emboss",
   "parameters" : [
      {
         "locked" : null,
         "value" : "@(!$(only))",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'all' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-all",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "all",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "@(!$(only))",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'comment' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-comment",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "comment",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "$(full)",
         "args" : "",
         "chained" : 0,
         "description" : "This displays a short name for the file containing the server definition",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-defined",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "defined",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "$(full)",
         "args" : "",
         "chained" : 0,
         "description" : "This displays the search fields that can be used on this server, other than the standard 'id' or 'acc' fields.",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-fields",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "fields",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "N",
         "args" : "",
         "chained" : 0,
         "description" : "Display all columns",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-full",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "full",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "@(!$(only))",
         "args" : "",
         "chained" : 0,
         "description" : "Display column headings",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-heading",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "heading",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "N",
         "args" : "",
         "chained" : 0,
         "description" : "Format output as an HTML table",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-html",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "html",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "@(!$(only))",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'id' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-id",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "id",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "$(full)",
         "args" : "",
         "chained" : 0,
         "description" : "This displays the access methods that can be used on this server, for all, query or ID access",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-methods",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "methods",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "Y",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'cachefile' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-nocachefile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "nocachefile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "Y",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'count' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-nocount",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "nocount",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "Y",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'URL' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-nourl",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "nourl",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "N",
         "args" : "",
         "chained" : 0,
         "description" : "This is a way of shortening the command line if you only want a few standard columns to be displayed. Instead of specifying: '-nohead -notype -noid -noquery -noall' to get only the comment output, you can specify '-only -comment'",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-only",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "toggle",
         "param" : "only",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "stdout",
         "args" : "",
         "chained" : 0,
         "description" : "Output file name",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-outfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "outfile",
         "param" : "outfile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "@(!$(only))",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'qry' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-query",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "query",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "@(!$(only))",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'scope' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-scope",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "scope",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Name of a single server to give information on (Any string)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-server",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "server",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "$(full)",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'version' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-serverversion",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "serverversion",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "*",
         "args" : "",
         "chained" : 0,
         "description" : "Show type(s) (Values: Protein (Protein sequences); Nucleic (Nucleotide sequences); Sequence (Any sequence data); Protfeatures (Protein features); Nucfeatures (Nucleotide features); Features (Any feature table data); Obo (OBO ontology data); Resource (Data resource); Taxonomy (Taxonomy data); Assembly (Assembled short read data); Text (text data); Html (HTML text data); Xml (XML text data); Unknown (Unspecified datatype to be defined for each database))",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-showtypes",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "menu",
         "param" : "showtypes",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "type",
         "args" : "",
         "chained" : 0,
         "description" : "Sort by (Values: defined (Definition file short name); type (Datatype))",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-sortby",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "menu",
         "param" : "sortby",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "@(!$(only))",
         "args" : "",
         "chained" : 0,
         "description" : "Display 'type' column",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-type",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "type",
         "paramFunction" : ""
      }
   ],
   "linkurl" : "http://emboss.sourceforge.net/apps/release/6.4/emboss/apps/showserver.html",
   "ordinal" : 0,
   "notes" : "",
   "url" : "http://www.ebi.ac.uk/Tools/emboss",
   "type" : "display"
}

