{
   "owner" : "agua",
   "location" : "bin/dbiblast",
   "executor" : "",
   "installdir" : "/aguadev/apps/emboss",
   "version" : "6.4.0.0",
   "name" : "dbiblast",
   "localonly" : "0",
   "description" : "Index a BLAST database",
   "package" : "emboss",
   "parameters" : [
      {
         "locked" : null,
         "value" : "unknown",
         "args" : "",
         "chained" : 0,
         "description" : "Blast index version (Values: 1 (wublast and setdb/pressdb); 2 (formatdb); 0 (unknown))",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-blastversion",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "menu",
         "param" : "blastversion",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "00/00/00",
         "args" : "",
         "chained" : 0,
         "description" : "Index date (Date string dd/mm/yy)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-date",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "date",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Database name (Any string from 2 to 19 characters, matching regular expression /[A-z][A-z0-9_]+/)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-dbname",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "dbname",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : ".",
         "args" : "",
         "chained" : 0,
         "description" : "Database directory",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-directory",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "directory",
         "param" : "directory",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Wildcard filename(s) to exclude (Any string)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-exclude",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "exclude",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "acc",
         "args" : "",
         "chained" : 0,
         "description" : "Index fields (Values: acc (acnum accession number index); sv (seqvn sequence version and gi number index); des (des description index))",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-fields",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "menu",
         "param" : "fields",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "Database name",
         "args" : "",
         "chained" : 0,
         "description" : "Wildcard database filename (Any string)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-filenames",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "filenames",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : ".",
         "args" : "",
         "chained" : 0,
         "description" : "Index file output directory",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-indexoutdir",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "outdir",
         "param" : "indexoutdir",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "0",
         "args" : "",
         "chained" : 0,
         "description" : "Maximum index length (Integer 0 or more)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-maxindex",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "maxindex",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "Y",
         "args" : "",
         "chained" : 0,
         "description" : "Clean up temporary files",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-nocleanup",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "nocleanup",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "Y",
         "args" : "",
         "chained" : 0,
         "description" : "Use system sort utility",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-nosystemsort",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "nosystemsort",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "*.dbiblast",
         "args" : "",
         "chained" : 0,
         "description" : "General log output file",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-outfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "outfile",
         "param" : "outfile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "0.0",
         "args" : "",
         "chained" : 0,
         "description" : "Release number (Any string up to 9 characters)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-release",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "release",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "unknown",
         "args" : "",
         "chained" : 0,
         "description" : "Sequence type (Values: N (nucleic); P (protein); ? (unknown))",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-seqtype",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "menu",
         "param" : "seqtype",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "-T . -k 1,1",
         "args" : "",
         "chained" : 0,
         "description" : "Sort options, typically '-T .' to use current directory for work files and '-k 1,1' to force GNU sort to use the first field (Any string)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-sortoptions",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "string",
         "param" : "sortoptions",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Use FASTA source file",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-sourcefile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "sourcefile",
         "paramFunction" : ""
      }
   ],
   "linkurl" : "http://emboss.sourceforge.net/apps/release/6.4/emboss/apps/dbiblast.html",
   "ordinal" : 0,
   "notes" : "",
   "url" : "http://www.ebi.ac.uk/Tools/emboss",
   "type" : "index"
}

