{
   "status" : "",
   "submit" : null,
   "ordinal" : null,
   "owner" : "anonymous",
   "locked" : 0,
   "location" : null,
   "executor" : "",
   "name" : "fastqc",
   "duration" : "",
   "description" : "",
   "stopped" : "",
   "parameters" : [
      {
         "value" : "Print this help file and exit",
         "description" : "",
         "discretion" : "",
         "params" : "",
         "ordinal" : 1,
         "argument" : "--help",
         "format" : "",
         "paramfile" : "",
         "type" : "",
         "category" : "",
         "param" : "help",
         "paramFunction" : ""
      },
      {
         "value" : "Print the version of the program and exit",
         "description" : "",
         "discretion" : "",
         "params" : "",
         "ordinal" : 2,
         "argument" : "--version",
         "format" : "",
         "paramfile" : "",
         "type" : "",
         "category" : "",
         "param" : "version",
         "paramFunction" : ""
      },
      {
         "value" : "Create all output files in the specified output directory. Please note that this directory must exist as the program will not create it.  If this option is not set then the output file for each sequence file is created in the same directory as the sequence file which was processed.",
         "description" : "",
         "discretion" : "",
         "params" : "",
         "ordinal" : 3,
         "argument" : "--outdir",
         "format" : "",
         "paramfile" : "",
         "type" : "",
         "category" : "",
         "param" : "outdir",
         "paramFunction" : ""
      },
      {
         "value" : "If set then the zipped output file will be uncomressed in the same directory after it has been created.  By default this option will be set if fastqc is run in non-interactive mode.",
         "description" : "",
         "discretion" : "",
         "params" : "",
         "ordinal" : 4,
         "argument" : "--extract",
         "format" : "",
         "paramfile" : "",
         "type" : "",
         "category" : "",
         "param" : "extract",
         "paramFunction" : ""
      },
      {
         "value" : "Do not uncompress the output file after creating it.  You should set this option if you do not wish to uncompress the output when running in non-interactive mode.",
         "description" : "",
         "discretion" : "",
         "params" : "",
         "ordinal" : 5,
         "argument" : "--noextract",
         "format" : "",
         "paramfile" : "",
         "type" : "",
         "category" : "",
         "param" : "noextract",
         "paramFunction" : ""
      },
      {
         "value" : "Disable grouping of bases for reads >50bp. All reports will show data for every base in the read.  WARNING: Using this option will cause fastqc to crash and burn if you use it on really long reads, and your plots may end up a ridiculous size. You have been warned!",
         "description" : "",
         "discretion" : "",
         "params" : "",
         "ordinal" : 6,
         "argument" : "--nogroup",
         "format" : "",
         "paramfile" : "",
         "type" : "",
         "category" : "",
         "param" : "nogroup",
         "paramFunction" : ""
      },
      {
         "value" : "Bypasses the normal sequence file format detection and forces the program to use the specified format.  Valid formats are bam,sam,bam_mapped,sam_mapped and fastq",
         "description" : "",
         "discretion" : "",
         "params" : "",
         "ordinal" : 7,
         "argument" : "--format",
         "format" : "",
         "paramfile" : "",
         "type" : "",
         "category" : "",
         "param" : "format",
         "paramFunction" : ""
      },
      {
         "value" : "Specifies the number of files which can be processed simultaneously.  Each thread will be allocated 250MB of memory so you shouldn't run more threads than your available memory will cope with, and not more than 6 threads on a 32 bit machine",
         "description" : "",
         "discretion" : "",
         "params" : "",
         "ordinal" : 8,
         "argument" : "--threads",
         "format" : "",
         "paramfile" : "",
         "type" : "",
         "category" : "",
         "param" : "threads",
         "paramFunction" : ""
      },
      {
         "value" : "Specifies a non-default file which contains the list of contaminants to screen overrepresented sequences against. The file must contain sets of named contaminants in the form name[tab]sequence.  Lines prefixed with a hash will be ignored.",
         "description" : "",
         "discretion" : "",
         "params" : "",
         "ordinal" : 9,
         "argument" : "--contaminants",
         "format" : "",
         "paramfile" : "",
         "type" : "",
         "category" : "",
         "param" : "contaminants",
         "paramFunction" : ""
      }
   ],
   "notes" : "",
   "started" : "",
   "type" : null,
   "queued" : ""
}

