{
   "owner" : "agua",
   "location" : "bin/aligners/elandHeader.pl",
   "executor" : "/usr/bin/perl",
   "installdir" : "/agua/0.6/t/bin/Agua/Ops/Install/outputs/bioapps",
   "version" : "0.6.0",
   "name" : "elandHeader",
   "localonly" : "0",
   "description" : "Convert incorrect header formats to the simple header format accepted by ELAND and other aligners matching this regex: \t ",
   "package" : "bioapps",
   "parameters" : [
      {
         "locked" : "0",
         "value" : "%project%/%workflow%/sequence.txt",
         "args" : "output.outputfile.value",
         "description" : "FASTQ file not in ELAND format (for use with ELAND_standalone.pl)",
         "discretion" : "essential",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--inputfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "readfile ",
         "param" : "inputfile",
         "paramFunction" : ""
      },
      {
         "locked" : "1",
         "value" : "myLabel",
         "args" : "",
         "description" : "Add this to the filenames of the converted files to identify the experiment/data test this",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "1",
         "argument" : "--label",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "label",
         "param" : "label",
         "paramFunction" : ""
      },
      {
         "locked" : "1",
         "value" : "",
         "args" : "",
         "description" : "Complementary FASTQ reads file for input files ",
         "discretion" : "",
         "inputParams" : "",
         "ordinal" : "1",
         "argument" : "--matefile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "matefile",
         "param" : "matefile",
         "paramFunction" : ""
      },
      {
         "locked" : "1",
         "value" : "",
         "args" : "",
         "description" : "",
         "discretion" : "\t",
         "inputParams" : "",
         "ordinal" : "1",
         "argument" : "--matefile",
         "format" : "",
         "paramtype" : "output",
         "valuetype" : "file",
         "category" : "matefile",
         "param" : "matefile",
         "paramFunction" : null
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "",
         "discretion" : "\t",
         "inputParams" : "",
         "ordinal" : "1",
         "argument" : "",
         "format" : "",
         "paramtype" : "output",
         "valuetype" : "file",
         "category" : "readfile",
         "param" : "readfile",
         "paramFunction" : null
      }
   ],
   "ordinal" : null,
   "notes" : "http://www.aguadev.org/confluence/display/howto/Bioapps+API",
   "url" : " ",
   "type" : "converter"
}

