{
   "owner" : "admin",
   "location" : "bin/einverted",
   "executor" : "",
   "installdir" : "/aguadev/apps/emboss",
   "version" : "6.6.0.0",
   "name" : "einverted",
   "localonly" : "0",
   "description" : "Find inverted repeats in nucleotide sequences",
   "package" : "emboss",
   "parameters" : [
      {
         "locked" : null,
         "value" : "12",
         "args" : "",
         "chained" : 0,
         "description" : "Gap penalty (Integer 0 or more)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-gap",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "gap",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "3",
         "args" : "",
         "chained" : 0,
         "description" : "Match score (Integer 0 or more)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-match",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "match",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "2000",
         "args" : "",
         "chained" : 0,
         "description" : "Maximum separation between the start of repeat and the end of the inverted repeat. (Integer 0 or more)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-maxrepeat",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "maxrepeat",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "-4",
         "args" : "",
         "chained" : 0,
         "description" : "Mismatch score (Integer up to 0)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-mismatch",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "mismatch",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "*.einverted",
         "args" : "",
         "chained" : 0,
         "description" : "Sanger Centre program inverted output file",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-outfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "outfile",
         "param" : "outfile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "<sequence>.<format>",
         "args" : "",
         "chained" : 0,
         "description" : "The sequence of the inverted repeat regions without gap characters.",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-outseq",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "seqout",
         "param" : "outseq",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Nucleotide sequence(s) filename and optional format, or reference (input USA)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-sequence",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "seqall",
         "param" : "sequence",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "50",
         "args" : "",
         "chained" : 0,
         "description" : "Minimum score threshold (Integer 0 or more)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-threshold",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "threshold",
         "paramFunction" : ""
      }
   ],
   "linkurl" : "http://emboss.sourceforge.net/apps/release/6.4/emboss/apps/einverted.html",
   "ordinal" : 0,
   "notes" : "",
   "url" : "http://archive.ubuntu.com/ubuntu/pool/universe/e/emboss/emboss_$version.orig.tar.gz",
   "type" : "repeat"
}

