{
   "owner" : "agua",
   "location" : "bin/aligners/ELAND.pl",
   "executor" : "/usr/bin/perl",
   "installdir" : "/agua/0.6/t/bin/Agua/Ops/Install/outputs/bioapps",
   "version" : "0.6.0",
   "name" : "ELAND",
   "localonly" : "0",
   "description" : "Solexa/Illumina short read aligner (max 32 bps aligned)",
   "package" : "bioapps",
   "parameters" : [
      {
         "locked" : "0",
         "value" : "1",
         "args" : "",
         "description" : "Clean run (remove old splitfile)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--clean",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "flag",
         "category" : "clean",
         "param" : "clean",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "input.outputdir.value",
         "description" : "Chromosome-specific *bam files containing aligned reads",
         "discretion" : "optional",
         "inputParams" : "outputdir",
         "ordinal" : "1",
         "argument" : "",
         "format" : "",
         "paramtype" : "output",
         "valuetype" : "files",
         "category" : "hits",
         "param" : "hits",
         "paramFunction" : "return outputdir + /chr*/hit.bam;"
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "output.readfile.value,input.readfile.value",
         "description" : "Solexa FASTQ format sequence file",
         "discretion" : "essential",
         "inputParams" : "input1,input2",
         "ordinal" : "0",
         "argument" : "--inputfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "inputfile",
         "param" : "inputfile",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "fastq",
         "args" : "",
         "description" : "Type of input sequence. Valid inputs: fastq, fasta, export or qseq",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--inputtype",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "inputtype",
         "param" : "inputtype",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "myLabel",
         "args" : "input.label.value",
         "description" : "Label describing the data or experiment",
         "discretion" : "required",
         "inputParams" : "InputParams",
         "ordinal" : "0",
         "argument" : "--label",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "label",
         "param" : "label",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "output.matefile.value,input.matefile.value",
         "description" : "Paired-end mate file complementary to inputfile (e.g., s_1_2_sequence.fastq)",
         "discretion" : "optional",
         "inputParams" : "input1,input2",
         "ordinal" : "0",
         "argument" : "--matefile",
         "format" : "fastq",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "matefile",
         "param" : "matefile",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "%project%/%workflow%",
         "args" : "",
         "description" : "Print ELAND alignment files to this directory (will create the directory if it does not exist)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--outputdir",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "outputdir",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Paired read analysis parameters to pass to pickBestPair. Default: '--circular' (treats all chromosomes as circular).",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--pairparams",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "pairparams",
         "param" : "pairparams",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Quality value of all bases in fasta mode (Default: 30)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--quality",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "quality",
         "param" : "quality",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "1000000",
         "args" : "",
         "description" : "Number of reads per sub-file",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--reads",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "reads",
         "param" : "reads",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "%project%/%workflow%",
         "args" : "",
         "description" : "Directory containing squashed reference genome files",
         "discretion" : "essential",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--referencedir",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "referencedir",
         "param" : "referencedir",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "Length of read used for ELAND alignment (Default: min. of seedlength and 32)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--seedlength",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "seedlength",
         "param" : "seedlength",
         "paramFunction" : ""
      },
      {
         "locked" : "1",
         "value" : "human",
         "args" : "",
         "description" : "Name of species, e.g., human, mouse, rat.",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--species",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "species",
         "param" : "species",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--splitfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "splitfile",
         "param" : "splitfile",
         "paramFunction" : ""
      }
   ],
   "ordinal" : null,
   "notes" : " ",
   "url" : "http://www.aguadev.org/confluence/display/howto/Bioapps+API",
   "type" : "aligner"
}

