{
   "owner" : "agua",
   "location" : "bin/filters/filterSNP.pl",
   "executor" : "/usr/bin/perl",
   "installdir" : "/agua/0.6/t/bin/Agua/Ops/Install/outputs/bioapps",
   "version" : "0.6.0",
   "name" : "filterSNP",
   "localonly" : "0",
   "description" : "Filter SNPs by quality, coverage, etc.",
   "package" : "bioapps",
   "parameters" : [
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--chromosome",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "chromosome",
         "param" : "chromosome",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--coverage",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "coverage",
         "param" : "coverage",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--filename",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "filename",
         "param" : "filename",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "%project%/%workflow%",
         "args" : "output.outputdir.value",
         "description" : "Directory with one subdirectory per reference chromosome, each containing an out.sav extended pileup format file of predicted SNPs and annotation information",
         "discretion" : "essential",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--inputdir",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "inputdir",
         "param" : "inputdir",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "%project%/%workflow%",
         "args" : "input.inputdir.value",
         "description" : "Directory with one subdirectory per reference chromosome, each containing an out.sav.flt filterSNP output file",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--outputdir",
         "format" : "",
         "paramtype" : "output",
         "valuetype" : "directory",
         "category" : "outputdir",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--quality",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "quality",
         "param" : "quality",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--sense",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "sense",
         "param" : "sense",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "",
         "args" : "",
         "description" : "",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--species",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "species",
         "param" : "species",
         "paramFunction" : ""
      }
   ],
   "ordinal" : null,
   "notes" : " ",
   "url" : "http://www.aguadev.org/confluence/display/howto/Bioapps+API",
   "type" : "report"
}

