{
   "owner" : "agua",
   "location" : "bin/distmat",
   "executor" : "",
   "installdir" : "/aguadev/apps/emboss",
   "version" : "6.4.0.0",
   "name" : "distmat",
   "localonly" : "0",
   "description" : "Create a distance matrix from a multiple sequence alignment",
   "package" : "emboss",
   "parameters" : [
      {
         "locked" : null,
         "value" : "N",
         "args" : "",
         "chained" : 0,
         "description" : "Option to use the ambiguous codes in the calculation of the Jukes-Cantor method or if the sequences are proteins.",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-ambiguous",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "ambiguous",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "N",
         "args" : "",
         "chained" : 0,
         "description" : "This will force the calculation of parameter 'a' in the Jin-Nei Gamma distance calculation, otherwise the default is 1.0 (see -parametera option).",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-calculatea",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "boolean",
         "category" : "boolean",
         "param" : "calculatea",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "0.",
         "args" : "",
         "chained" : 0,
         "description" : "Option to weight gaps in the uncorrected (nucleotide) and Jukes-Cantor distance methods. (Any numeric value)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-gapweight",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "decimal",
         "category" : "decimal",
         "param" : "gapweight",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "0",
         "args" : "",
         "chained" : 0,
         "description" : "Multiple substitution correction methods for nucleotides. (Values: 0 (Uncorrected); 1 (Jukes-Cantor); 2 (Kimura); 3 (Tamura); 4 (Tajima-Nei); 5 (Jin-Nei Gamma))",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-nucmethod",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "menu",
         "param" : "nucmethod",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "*.distmat",
         "args" : "",
         "chained" : 0,
         "description" : "Phylip distance matrix output file",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-outfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "outfile",
         "param" : "outfile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "1.0",
         "args" : "",
         "chained" : 0,
         "description" : "User defined parameter 'a' to be use in the Jin-Nei Gamma distance calculation. The suggested value to be used is 1.0 (Jin et al.) and this is the default. (Any numeric value)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-parametera",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "decimal",
         "category" : "decimal",
         "param" : "parametera",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "123",
         "args" : "",
         "chained" : 0,
         "description" : "Choose base positions to analyse in each codon i.e. 123 (all bases), 12 (the first two bases), 1, 2, or 3 individual bases. (Any integer value)",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-position",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "integer",
         "category" : "integer",
         "param" : "position",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "0",
         "args" : "",
         "chained" : 0,
         "description" : "Multiple substitution correction methods for proteins. (Values: 0 (Uncorrected); 1 (Jukes-Cantor); 2 (Kimura Protein))",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-protmethod",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "menu",
         "param" : "protmethod",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "File containing a sequence alignment.",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-sequence",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "infile",
         "param" : "sequence",
         "paramFunction" : ""
      }
   ],
   "linkurl" : "http://emboss.sourceforge.net/apps/release/6.4/emboss/apps/distmat.html",
   "ordinal" : 0,
   "notes" : "",
   "url" : "http://www.ebi.ac.uk/Tools/emboss",
   "type" : "alignment"
}

