{
   "owner" : "agua",
   "location" : "bin/btwisted",
   "executor" : "",
   "installdir" : "/aguadev/apps/emboss",
   "version" : "6.4.0.0",
   "name" : "btwisted",
   "localonly" : "0",
   "description" : "Calculate the twisting in a B-DNA sequence",
   "package" : "emboss",
   "parameters" : [
      {
         "locked" : null,
         "value" : "Eangles.dat",
         "args" : "",
         "chained" : 0,
         "description" : "DNA base pair twist angle data file",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-angledata",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "infile",
         "param" : "angledata",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "Eenergy.dat",
         "args" : "",
         "chained" : 0,
         "description" : "DNA base pair stacking energies data file",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-energydata",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "infile",
         "param" : "energydata",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "*.btwisted",
         "args" : "",
         "chained" : 0,
         "description" : "Output file name",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-outfile",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "file",
         "category" : "outfile",
         "param" : "outfile",
         "paramFunction" : ""
      },
      {
         "locked" : null,
         "value" : "",
         "args" : "",
         "chained" : 0,
         "description" : "Nucleotide sequence filename and optional format, or reference (input USA)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : 0,
         "argument" : "-sequence",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "sequence",
         "param" : "sequence",
         "paramFunction" : ""
      }
   ],
   "linkurl" : "http://emboss.sourceforge.net/apps/release/6.4/emboss/apps/btwisted.html",
   "ordinal" : 0,
   "notes" : "",
   "url" : "http://www.ebi.ac.uk/Tools/emboss",
   "type" : "structure"
}

