{
   "owner" : "agua",
   "location" : "bin/snp/SAV.pl",
   "executor" : "/usr/bin/perl",
   "installdir" : "/agua/0.6/t/bin/Agua/Ops/Install/outputs/bioapps",
   "version" : "0.6.0",
   "name" : "SAV",
   "localonly" : "0",
   "description" : "SNP Annotation and Verification",
   "package" : "bioapps",
   "parameters" : [
      {
         "locked" : "0",
         "value" : "snp130",
         "args" : "",
         "description" : "dbSNP version for given species",
         "discretion" : "optional",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--dbsnp",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "dbsnp",
         "param" : "dbsnp",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "%project%/%workflow%",
         "args" : "input.outputdir.value,output.outputdir.value",
         "description" : "Directory with one subdirectory per reference chromosome, each containing an out.sam or out.bam alignment output file",
         "discretion" : "required",
         "inputParams" : "outdir1,outdir2",
         "ordinal" : "0",
         "argument" : "--inputdir",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "inputdir",
         "param" : "inputdir",
         "paramFunction" : "if ( outdir1 != null && outdir1 !=  ) return outdir1; if ( outdir2 != null && outdir2 !=  ) return outdir2;"
      },
      {
         "locked" : "0",
         "value" : "%project%/%workflow%",
         "args" : "input.inputdir.value",
         "description" : "Directory with one subdirectory per reference chromosome, each containing an out.sav output file",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--outputdir",
         "format" : "",
         "paramtype" : "output",
         "valuetype" : "directory",
         "category" : "outputdir",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "/nethome/bioinfo/data/sequence/chromosomes/human/hg19/fasta",
         "args" : "",
         "description" : "Location of directory containing chr*.fa reference files",
         "discretion" : "essential",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--referencedir",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "directory",
         "category" : "referencedir",
         "param" : "referencedir",
         "paramFunction" : ""
      },
      {
         "locked" : "0",
         "value" : "human",
         "args" : "",
         "description" : "Name of the reference species (e.g., human, mouse)",
         "discretion" : "required",
         "inputParams" : "",
         "ordinal" : "0",
         "argument" : "--species",
         "format" : "",
         "paramtype" : "input",
         "valuetype" : "string",
         "category" : "species",
         "param" : "species",
         "paramFunction" : ""
      }
   ],
   "ordinal" : null,
   "notes" : "Call SNPs in pileup format from .SAM or .BAM file generated for each chromosome of the target species (DEFAULT: human hg19) and compare with dbSNP (DEFAULT: dbsnp130)",
   "url" : "http://www.aguadev.org/confluence/display/howto/Bioapps+API",
   "type" : "pipeline"
}

